Repository MLH-Fellowship/0.5.2-cms, pull requests merged in 2020-06, with the labels that each got.

#12 added file structure for flask app
  .gitignore
  flask_app/__init__.py
  flask_app/auth.py
  flask_app/db.py
  flask_app/webFlask.py
  setup.py
Labels: webapp

#16 Set up react frontend and connected it to flask backend
  .DS_Store
  .gitignore
  README.md
  client/.DS_Store
  client/config/env.js
  client/config/getHttpsConfig.js
  client/config/jest/cssTransform.js
  client/config/jest/fileTransform.js
  client/config/modules.js
  client/config/paths.js
  client/config/pnpTs.js
  client/config/webpack.config.js
  client/config/webpackDevServer.config.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/scripts/build.js
  client/scripts/start.js
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  client/src/styles/App.css
  client/src/utilities.js
  flask_app/webFlask.py
  server/.DS_Store
  server/__init__.py
  server/app.py
  server/auth.py
  server/db.py
  server/requirements.txt
  server/templates/index.html
Labels: webapp

#22 Set up frontend routing and homepage
  .DS_Store
  client/.DS_Store
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/.DS_Store
  client/src/App.js
  client/src/assets/background.svg
  client/src/components/.DS_Store
  client/src/components/Home.js
  client/src/components/MapView.js
  client/src/styles/App.css
  server/templates/index.html
Labels: webapp

#30 Implemented remaining static frontend pages
  .DS_Store
  .gitignore
  client/.DS_Store
  client/package-lock.json
  client/package.json
  client/src/.DS_Store
  client/src/App.js
  client/src/assets/APAC.svg
  client/src/assets/Americas.svg
  client/src/assets/EMEA.svg
  client/src/assets/Global.svg
  client/src/components/.DS_Store
  client/src/components/Home.js
  client/src/components/modules/AddContactForm.js
  client/src/components/modules/Navbar.js
  client/src/components/pages/AllContacts.js
  client/src/components/pages/ContactBook.js
  client/src/components/pages/GroupPage.js
  client/src/components/pages/Home.js
  client/src/components/pages/MapView.js
  client/src/components/pages/Profile.js
  client/src/data.js
  client/src/pages.css
  client/src/styles/App.css
  client/src/styles/groups.css
  client/src/styles/home.css
  client/src/styles/navbar.css
  client/src/styles/profile.css
  server/.DS_Store
  server/app.py
  server/templates/index.html
Labels: webapp

#36 Prevent non-logged users from entering other pages
  client/src/App.js
  client/src/GlobalContext.js
  client/src/components/pages/AllContacts.js
  client/src/components/pages/ContactBook.js
  client/src/components/pages/GroupPage.js
  client/src/components/pages/Home.js
  client/src/components/pages/Profile.js
  server/app.py
Labels: bug

#40 Pages now read/write to Context store & Placeholder profiles
  client/src/GlobalContext.js
  client/src/assets/EMEA.svg
  client/src/components/modules/AddContactForm.js
  client/src/components/pages/AllContacts.js
  client/src/components/pages/ContactBook.js
  client/src/components/pages/GroupPage.js
  client/src/components/pages/Home.js
  client/src/components/pages/Profile.js
  client/src/styles/App.css
  client/src/styles/profile.css
  server/resources/auth.py
Labels: webapp

#41 Finish login and register system
  client/src/GlobalContext.js
  client/src/components/modules/Navbar.js
  client/src/components/pages/AllContacts.js
  client/src/components/pages/ContactBook.js
  client/src/components/pages/GroupPage.js
  client/src/components/pages/Home.js
  client/src/components/pages/Profile.js
  server/resources/auth.py
  server/templates/index.html
Labels: webapp

#47 Modified user model and linked frontend to backend
  .DS_Store
  client/src/GlobalContext.js
  client/src/components/modules/AddContactForm.js
  client/src/components/pages/AllContacts.js
  client/src/components/pages/ContactBook.js
  client/src/components/pages/GroupPage.js
  client/src/components/pages/Home.js
  client/src/components/pages/Profile.js
  client/src/styles/profile.css
  server/.DS_Store
  server/database/models.py
  server/resources/auth.py
  server/resources/contact.py
  server/resources/routes.py
  server/templates/index.html
Labels: bug, webapp
